version: '3'

services:
    web:
      build: .
      volumes:
        - .\WordPress:/var/www/html
      ports:
        - 80:80
    db:
      image: mysql:5.7
      volumes:
      - .\DB:/var/lib/mysql
      ports: 
        - 3306:3306
      environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: 1
        MYSQL_DATABASE: test


